name: replica_list_moteis
version: 1.0.0+1
description: "Réplica da tela de listagem de motéis do aplicativo Guia de Motéis GO (aba 'Ir Agora'), utilizando links como API mock."
publish_to: 'none'

environment:
  sdk: 3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.3.0
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  html: ^0.15.5

flutter:
  uses-material-design: true
