name: replica_list_moteis
version: 1.0.0+1
description: "Réplica da tela de listagem de motéis do aplicativo Guia de Motéis GO (aba 'Ir Agora'), utilizando links como API mock."
publish_to: 'none'

environment:
  sdk: 3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  http: ^1.3.0
  provider: ^6.1.2
  cached_network_image: ^3.4.1
  html: ^0.15.5
  test: ^1.25.7
  mockito: ^5.4.4

flutter:
  uses-material-design: true

  assets:
    - assets/

flutter_native_splash:
  image: assets/logo/logo_red.png
  color: "#ffffff"
  android_12:
    image: assets/logo/logo_red.png
    color: "#ffffff"
